### ISSUE TITLE
Issue counter on Repositories page also counts PRs

### ISSUE THREAD

**Issue by AdamRaichu** [Mycelium-Mod-Network/Modtoberfest-Site#17]
The widget on the project card is labeled issues, but actually shows the combined count of issues and pull requests for the project.

![image](https://github.com/user-attachments/assets/e06b2e3e-673c-483a-9a97-7941e296048e)

![image](https://github.com/user-attachments/assets/99e2b2de-3a37-414b-bcc3-5a4ce4332029)

**Comment by jaredlll08** [comment]
Unfortunately I am just displaying the data that github's api provides for the `open_issues_count`.

I think the only way to resolve this would be to count the issues ourselves, which would require *a lot* more API requests per repo, which I don't think is feasible unfortunately.

If anyone who is more knowledgeable on the github API can chime in an tell me an easy way to get the data, I would appreciate it.
