### ISSUE TITLE
Long loading time on repository submit page

### ISSUE THREAD

**Issue by UpcraftLP** [Mycelium-Mod-Network/Modtoberfest-Site#6]
the repo submit page (`/repositories/submit`) loads very slowly (measured a delay of around 4 seconds for the initial response, leading to over 6 seconds to render the entire page).

This happens without any visual loading indication, making the button leading to that page seem like it isn't working at all, until the page eventually loads.

**Comment by jaredlll08** [comment]
Unfortunately I can't communicate with the github API any faster 😅 

So I hope a progress bar to show that stuff is happening is fine
